name: diu
description: DIU Routine — student offline class routine
publish_to: "none"
version: 0.1.1+5

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  provider: ^6.1.5
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  flutter_local_notifications: ^22.3.0
  timezone: ^0.11.1
  flutter_timezone: ^5.1.0
  pdf: ^3.13.0
  pdfrx: ^2.4.8
  http: ^1.5.0
  rxdart: ^0.28.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/routine/
    - assets/icon/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FBF3EB"
  adaptive_icon_foreground: "assets/icon/app_icon.png"
  web:
    generate: true
    image_path: "assets/icon/app_icon.png"
    background_color: "#FBF3EB"
    theme_color: "#FBF3EB"
  windows:
    generate: true
    image_path: "assets/icon/app_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icon/app_icon.png"
  linux:
    generate: true
    image_path: "assets/icon/app_icon.png"
