import 'dart:typed_data';

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../domain/course_label.dart';
import '../domain/model/routine_day.dart';
import '../domain/model/routine_meta.dart';
import '../domain/model/student_summary.dart';

/// Builds the section weekly schedule PDF (days with classes only).
class SchedulePdfBuilder {
  static const _headerBlue = PdfColor.fromInt(0xFF1B4F8A);
  static const _diuBlue = PdfColor.fromInt(0xFF1E4B8C);
  static const _diuGreen = PdfColor.fromInt(0xFF2E8B3A);
  static const _grid = PdfColor.fromInt(0xFF6B7280);
  static const _muted = PdfColor.fromInt(0xFF6B7280);

  static Future<Uint8List> build({
    required String queryLabel,
    required RoutineMeta meta,
    required Map<RoutineDay, List<ClassBlock>> week,
  }) async {
    final doc = pw.Document();
    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.fromLTRB(28, 24, 28, 28),
        build: (context) => [
          _header(meta, queryLabel),
          pw.SizedBox(height: 18),
          pw.Center(
            child: pw.Text(
              'Class Schedule : $queryLabel',
              style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold),
            ),
          ),
          pw.SizedBox(height: 14),
          _scheduleTable(week),
        ],
      ),
    );
    return doc.save();
  }

  static pw.Widget _header(RoutineMeta meta, String queryLabel) {
    final qrPayload =
        'DIU Routine Scrapper\n$queryLabel\n${meta.department} ${meta.semester} v${meta.version}';
    return pw.Row(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Expanded(
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                'Powered By CSE Department',
                style: const pw.TextStyle(fontSize: 8, color: _muted),
              ),
              pw.SizedBox(height: 8),
              pw.Row(
                children: [
                  _logoMark(),
                  pw.SizedBox(width: 8),
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text(
                        'Daffodil International',
                        style: pw.TextStyle(
                          fontSize: 13,
                          fontWeight: pw.FontWeight.bold,
                          color: _diuBlue,
                        ),
                      ),
                      pw.Text(
                        'University',
                        style: pw.TextStyle(
                          fontSize: 13,
                          fontWeight: pw.FontWeight.bold,
                          color: _diuGreen,
                        ),
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ),
        pw.Column(
          children: [
            pw.Text(
              'Generated By',
              style: const pw.TextStyle(fontSize: 7, color: _muted),
            ),
            pw.SizedBox(height: 3),
            pw.BarcodeWidget(
              barcode: pw.Barcode.qrCode(),
              data: qrPayload,
              width: 52,
              height: 52,
              drawText: false,
            ),
            pw.SizedBox(height: 3),
            pw.Text(
              'Routine Scrapper',
              style: const pw.TextStyle(fontSize: 7, color: _muted),
            ),
            pw.Text(
              meta.version,
              style: pw.TextStyle(fontSize: 8, fontWeight: pw.FontWeight.bold),
            ),
          ],
        ),
      ],
    );
  }

  static pw.Widget _logoMark() {
    return pw.Container(
      width: 28,
      height: 32,
      decoration: pw.BoxDecoration(
        color: _diuGreen,
        borderRadius: pw.BorderRadius.circular(4),
      ),
      alignment: pw.Alignment.center,
      child: pw.Text(
        'DIU',
        style: pw.TextStyle(
          color: PdfColors.white,
          fontSize: 8,
          fontWeight: pw.FontWeight.bold,
        ),
      ),
    );
  }

  static pw.Widget _scheduleTable(
    Map<RoutineDay, List<ClassBlock>> week,
  ) {
    final rows = <pw.TableRow>[
      pw.TableRow(
        repeat: true,
        decoration: const pw.BoxDecoration(color: _headerBlue),
        children: [
          _headCell('Day'),
          _headCell('Course'),
          _headCell('Time Slot'),
          _headCell('Room'),
          _headCell('Teacher'),
        ],
      ),
    ];
    for (final entry in week.entries) {
      final blocks = entry.value;
      for (var index = 0; index < blocks.length; index++) {
        final block = blocks[index];
        rows.add(
          pw.TableRow(
            children: [
              _bodyCell(index == 0 ? entry.key.fullLabel : ''),
              _bodyCell(
                CourseLabel.format(
                  code: block.course,
                  group: block.group,
                  name: block.courseTitle.isNotEmpty ? block.courseTitle : null,
                ),
                align: pw.TextAlign.left,
              ),
              _bodyCell('${block.start}-${block.end}'),
              _bodyCell(block.room),
              _bodyCell(block.teacher),
            ],
          ),
        );
      }
    }
    return pw.Table(
      border: pw.TableBorder.all(color: _grid, width: 0.6),
      defaultVerticalAlignment: pw.TableCellVerticalAlignment.middle,
      columnWidths: const {
        0: pw.FlexColumnWidth(14),
        1: pw.FlexColumnWidth(42),
        2: pw.FlexColumnWidth(18),
        3: pw.FlexColumnWidth(22),
        4: pw.FlexColumnWidth(12),
      },
      children: rows,
    );
  }

  static pw.Widget _headCell(String text) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(horizontal: 6, vertical: 7),
      child: pw.Text(
        text,
        style: pw.TextStyle(
          color: PdfColors.white,
          fontSize: 9,
          fontWeight: pw.FontWeight.bold,
        ),
      ),
    );
  }

  static pw.Widget _bodyCell(
    String text, {
    pw.TextAlign align = pw.TextAlign.center,
  }) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(horizontal: 5, vertical: 6),
      child: pw.Text(
        text,
        textAlign: align,
        style: const pw.TextStyle(fontSize: 8.5),
      ),
    );
  }
}
